<?php

echo $this->html->open('form', ['method' => 'post', 'action' => $this->url('post', ['action' => 'create'])]);
    echo $this->html->text('data[name]', ['label' => 'Name'], 'index');
    echo '<br>';
    echo $this->html->textarea('data[description]', ['label' => 'Description'], 'description');
    echo '<br>';
    echo $this->html->text('data[class]', ['label' => 'Class'], $this->controller->modelClassName());
    echo '<br>';
    echo $this->html->tag('button', [], $this->html->tag('i', ['class' => 'fa fa-fw fa-plus']) . ' Create');
echo $this->html->open('close');

echo $this->html->a($this->url('post', ['action' => 'create']));

echo $this->view('post/read', ['result' => $posts]);
