<?php

$data = [
    'name' => 'index',
    'title' => 'Testing',
    'content' => [
        'class' => \hikari\cms\model\Page::className(),
    ],
];
echo $this->html->a($this->url('post', ['action' => 'create', 'data' => $data]), ['class' => 'button'], 'Create');

echo $this->html->open('pre');
	#var_dump($page);
echo $this->html->close('pre');

echo $this->html->open('pre');
	var_dump($pages);
echo $this->html->close('pre');

foreach($pages as $page) {
	echo $this->html->tag('hr');
	echo $this->html->a($this->url('post', ['action' => 'read', 'id' => (string)$page->id()]), [], $page->id());
	echo ' | ';
	echo $this->html->a($this->url('post', ['action' => 'dispose', 'id' => (string)$page->id()]), ['class' => 'button'], 'Delete');
}

#$page->delete();